SELECT
	#3
    TRIM(SALES_DATE) SALES_DATE
    , PRODUCT_ID
    , IF(USER_ID = -1, NULL, USER_ID) USER_ID #2
    , SUM(SALES_AMOUNT) SALES_AMOUNT
FROM
    (
    SELECT *
    FROM ONLINE_SALE ONL
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
    UNION ALL #1
    SELECT OFFLINE_SALE_ID, -1, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE OFL
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
    ) A
GROUP BY
    ONLINE_SALE_ID, PRODUCT_ID, USER_ID
ORDER BY
    1
    , 2
    , 3