-- 코드를 작성해주세요
SELECT A.ID ID,
    CASE
        WHEN A.SIZE <= 0.25 THEN 'CRITICAL'
        WHEN A.SIZE <= 0.5 THEN 'HIGH'
        WHEN A.SIZE <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END COLONY_NAME
FROM ( 
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) SIZE
    FROM ECOLI_DATA
) A
ORDER BY ID