-- 코드를 입력하세요
-- WITH TIME (HOUR) AS (
--     SELECT LEVEL - 1 FROM DUAL CONNECT BY LEVEL<23
-- )

-- SELECT B.HOUR, COUNT(A.ANIMAL_ID) AS "COUNT" FROM
-- TIME B
-- INNER JOIN
-- ANIMAL_OUTS A
-- ON B.HOUR = TO_NUMBER(TO_CHAR(A.DATETIME,'HH24'))
-- GROUP BY B.HOUR
-- ORDER BY B.HOUR


-- 0부터 23시까지의 시간 테이블 생성
WITH TIME (HOUR) AS (
    SELECT LEVEL - 1
    FROM DUAL
    CONNECT BY LEVEL <= 24
)
SELECT
    B.HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM
    TIME B
LEFT OUTER JOIN
    ANIMAL_OUTS A ON B.HOUR = TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24'))
GROUP BY
    B.HOUR
ORDER BY
    B.HOUR