-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') FROM
REST_REVIEW A
JOIN
(SELECT M.MEMBER_NAME, M.MEMBER_ID FROM
MEMBER_PROFILE M
JOIN
(SELECT MEMBER_ID, COUNT(*) COUNT FROM
REST_REVIEW
GROUP BY MEMBER_ID
) R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE COUNT = (SELECT * FROM (SELECT COUNT(*) FROM
               REST_REVIEW
               GROUP BY MEMBER_ID
               ORDER BY 1 DESC)
               WHERE ROWNUM=1)
) B
ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT        